version: '3.8'

services:
  app:
    build:
      context: ./main 
      dockerfile: ../Dockerfile  
    ports:
      - "3000:3000"
    volumes:
      - ./main:/app 
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

networks:
  default:
    external:
      name: proxynetwork
